More password things

diff --git a/software/test b/software/test
--- a/software/test
+++ b/software/test
@@ -8,17 +8,17 @@ if [ $# -ne 1 ]; then
     exit 1
 fi
 
-python3 -m venv /home
-source /home/bin/activate
+#python3 -m venv /home
+#source /home/bin/activate
 
-
-if [ $1 == "-e" ]; then
-    echo "Encrypting files in usb_test"
-    python3 poc.py e
-elif [ $1 == "-d" ]; then
-    echo "Decrypting files in usb_test"
-    python3 poc.py d
-else
-    echo "Invalid argument"
-    exit 1
-fi
+python3 poc.py
+#if [ $1 == "-e" ]; then
+#    echo "Encrypting files in usb_test"
+#    python3 poc.py e
+#elif [ $1 == "-d" ]; then
+#    echo "Decrypting files in usb_test"
+#    python3 poc.py d
+#else
+#    echo "Invalid argument"
+#    exit 1
+#fi
